#pragma once

#include "../compiler/always_inline.hpp"

namespace azine {
always_inline float acos(float x);
always_inline double acos(double x);
always_inline long double acos(long double x);
always_inline float acosh(float x);
always_inline double acosh(double x);
always_inline long double acosh(long double x);
always_inline float asin(float x);
always_inline double asin(double x);
always_inline long double asin(long double x);
always_inline float asinh(float x);
always_inline double asinh(double x);
always_inline long double asinh(long double x);
always_inline float atan(float x);
always_inline double atan(double x);
always_inline long double atan(long double x);
always_inline float atanh(float x);
always_inline double atanh(double x);
always_inline long double atanh(long double x);
always_inline float atan2(float x, float y);
always_inline double atan2(double x, double y);
always_inline long double atan2(long double x, long double y);
always_inline float cbrt(float x);
always_inline double cbrt(double x);
always_inline long double cbrt(long double x);
always_inline float ceil(float x);
always_inline double ceil(double x);
always_inline long double cail(long double x);
always_inline float copysign(float x, float y);
always_inline double copysign(double x, double y);
always_inline long double copysign(long double x, long double y);
always_inline float cos(float x);
always_inline double cos(double x);
always_inline long double cos(long double x);
always_inline float cosh(float x);
always_inline double cosh(double x);
always_inline long double cosh(long double x);
always_inline float erf(float x);
always_inline double erf(double x);
always_inline long double erf(long double x);
always_inline float erfc(float x);
always_inline double erfc(double x);
always_inline long double erfc(long double x);
always_inline float exp(float x);
always_inline double exp(double x);
always_inline long double exp(long double x);
always_inline float exp2(float x);
always_inline double exp2(double x);
always_inline long double exp2(long double x);
always_inline float expm1(float x);
always_inline double expm1(double x);
always_inline long double expm1(long double x);
always_inline float abs(float x);
always_inline double abs(double x);
always_inline long double abs(long double x);
always_inline float dim(float x, float y);
always_inline double dim(double x, double y);
always_inline long double dim(long double x, long double y);
always_inline float floor(float x);
always_inline double floor(double x);
always_inline long double floor(long double x);
always_inline float fma(float x, float y, float z);
always_inline double fma(double x, double y, double z);
always_inline long double fma(long double x, long double y, long double z);
always_inline float max(float x, float y);
always_inline double max(double x, double y);
always_inline long double max(long double x, long double y);
always_inline float min(float x, float y);
always_inline double min(double x, double y);
always_inline long double min(long double x, long double y);
always_inline float mod(float x, float y);
always_inline double mod(double x, double y);
always_inline long double mod(long double x, long double y);
always_inline float frexp(float x, int* y);
always_inline double frexp(double x, int* y);
always_inline long double frexp(long double x, int* y);
always_inline float hypot(float x, float y);
always_inline double hypot(double x, float y);
always_inline long double hypot(long double x, long double y);
always_inline int ilogb(float x);
always_inline int ilogb(double x);
always_inline int ilogb(long double x);
always_inline double j0(double x);
always_inline double j1(double x);
always_inline double jn(int x, double y);
always_inline float ldexp(float x, float y);
always_inline double ldexp(double x, double y);
always_inline long double ldexp(long double x, long double y);
always_inline float lgamma(float x);
always_inline double lgamma(double x);
always_inline long double lgamma(long double x);
always_inline long long llrint(float x);
always_inline long long llrint(double x);
always_inline long long llrint(long double x);
always_inline long long llround(float x);
always_inline long long llround(double x);
always_inline long long llround(long double x);
always_inline float log(float x);
always_inline double log(double x);
always_inline long double log(long double x);
always_inline float log10(float x);
always_inline double log10(double x);
always_inline long double log10(long double x);
always_inline float log1p(float x);
always_inline double log1p(double x);
always_inline long double log1p(long double x);
always_inline float log2(float x);
always_inline double log2(double x);
always_inline long double log2(long double x);
always_inline float logb(float x);
always_inline double logb(double x);
always_inline long double logb(long double x);
always_inline float lrint(float x);
always_inline double lrint(double x);
always_inline long double lrint(long double x);
always_inline float lround(float x);
always_inline double lround(double x);
always_inline long double lround(long double x);
always_inline float modf(float x, float* y);
always_inline double modf(double x, double* y);
always_inline long double modf(long double x, long double* y);
always_inline float nanf(const char* x);
always_inline double nan(const char* x);
always_inline long double nanl(const char* x);
always_inline float nearbyint(float x);
always_inline double nearbyint(double x);
always_inline long double nearbyint(long double x);
always_inline float nextafter(float x, float y);
always_inline double nextafter(double x, double y);
always_inline long double nextafter(long double x, long double y);
always_inline float nexttoward(float x, float y);
always_inline double nexttoward(double x, double y);
always_inline long double nexttoward(long double x, long double y);
always_inline float pow(float x, float y);
always_inline double pow(double x, double y);
always_inline long double pow(long double x, long double y);
always_inline float remainder(float x, float y);
always_inline double remainder(double x, double y);
always_inline long double remainder(long double x, long double y);
always_inline float remquo(float x, float y, int* z);
always_inline double remquo(double x, double y, int* z);
always_inline long double remquo(long double x, long double y, int* z);
always_inline float rint(float x);
always_inline double rint(double x);
always_inline long double rint(long double x);
always_inline float round(float x);
always_inline double round(double x);
always_inline long double round(long double x);
always_inline float scalbln(float x, long y);
always_inline double scalbln(double x, long y);
always_inline long double scalbln(long double x, long y);
always_inline float scalbn(float x, int y);
always_inline double scalbn(double x, int y);
always_inline long double scalbn(long double x, int y);
always_inline float sin(float x);
always_inline double sin(double x);
always_inline long double sin(long double x);
always_inline float sinh(float x);
always_inline double sinh(double x);
always_inline long double sinh(long double x);
always_inline float sqrt(float x);
always_inline double sqrt(double x);
always_inline long double sqrt(long double x);
always_inline float tan(float x);
always_inline double tan(double x);
always_inline long double tan(long double x);
always_inline float tanh(float x);
always_inline double tanh(double x);
always_inline long double tanh(long double x);
always_inline float tgamma(float x);
always_inline double tgamma(double x);
always_inline long double tgamma(long double x);
always_inline float trunc(float x);
always_inline double trunc(double x);
always_inline long double trunc(long double x);
always_inline double y0(double x);
always_inline double y1(double x);
always_inline double yn(int x, double y);
}