#pragma once

namespace azine {
using float_t = float;
using double_t = double;

constexpr float acos(float x);
constexpr double acos(double x);
constexpr long double acos(long double x);
constexpr float acosh(float x);
constexpr double acosh(double x);
constexpr long double acosh(long double x);
constexpr float asin(float x);
constexpr double asin(double x);
constexpr long double asin(long double x);
constexpr float asinh(float x);
constexpr double asinh(double x);
constexpr long double asinh(long double x);
constexpr float atan(float x);
constexpr double atan(double x);
constexpr long double atan(long double x);
constexpr float atanh(float x);
constexpr double atanh(double x);
constexpr long double atanh(long double x);
constexpr float atan2(float x, float y);
constexpr double atan2(double x, double y);
constexpr long double atan2(long double x, long double y);
constexpr float cbrt(float x);
constexpr double cbrt(double x);
constexpr long double cbrt(long double x);
constexpr float ceil(float x);
constexpr double ceil(double x);
constexpr long double cail(long double x);
constexpr float copysign(float x, float y);
constexpr double copysign(double x, double y);
constexpr long double copysign(long double x, long double y);
constexpr float cos(float x);
constexpr double cos(double x);
constexpr long double cos(long double x);
constexpr float cosh(float x);
constexpr double cosh(double x);
constexpr long double cosh(long double x);
constexpr float erf(float x);
constexpr double erf(double x);
constexpr long double erf(long double x);
constexpr float erfc(float x);
constexpr double erfc(double x);
constexpr long double erfc(long double x);
constexpr float exp(float x);
constexpr double exp(double x);
constexpr long double exp(long double x);
constexpr float exp2(float x);
constexpr double exp2(double x);
constexpr long double exp2(long double x);
constexpr float expm1(float x);
constexpr double expm1(double x);
constexpr long double expm1(long double x);
constexpr float abs(float x);
constexpr double abs(double x);
constexpr long double abs(long double x);
constexpr float dim(float x, float y);
constexpr double dim(double x, double y);
constexpr long double dim(long double x, long double y);
constexpr float floor(float x);
constexpr double floor(double x);
constexpr long double floor(long double x);
constexpr float fma(float x, float y, float z);
constexpr double fma(double x, double y, double z);
constexpr long double fma(long double x, long double y, long double z);
constexpr float max(float x, float y);
constexpr double max(double x, double y);
constexpr long double max(long double x, long double y);
constexpr float min(float x, float y);
constexpr double min(double x, double y);
constexpr long double min(long double x, long double y);
constexpr float mod(float x, float y);
constexpr double mod(double x, double y);
constexpr long double mod(long double x, long double y);
constexpr float frexp(float x, int* y);
constexpr double frexp(double x, int* y);
constexpr long double frexp(long double x, int* y);
constexpr float hypot(float x, float y);
constexpr double hypot(double x, float y);
constexpr long double hypot(long double x, long double y);
constexpr int ilogb(float x);
constexpr int ilogb(double x);
constexpr int ilogb(long double x);
constexpr double j0(double x);
constexpr double j1(double x);
constexpr double jn(int x, double y);
constexpr float ldexp(float x, float y);
constexpr double ldexp(double x, double y);
constexpr long double ldexp(long double x, long double y);
constexpr float lgamma(float x);
constexpr double lgamma(double x);
constexpr long double lgamma(long double x);
constexpr long long llrint(float x);
constexpr long long llrint(double x);
constexpr long long llrint(long double x);
constexpr long long llround(float x);
constexpr long long llround(double x);
constexpr long long llround(long double x);
constexpr float log(float x);
constexpr double log(double x);
constexpr long double log(long double x);
constexpr float log10(float x);
constexpr double log10(double x);
constexpr long double log10(long double x);
constexpr float log1p(float x);
constexpr double log1p(double x);
constexpr long double log1p(long double x);
constexpr float log2(float x);
constexpr double log2(double x);
constexpr long double log2(long double x);
constexpr float logb(float x);
constexpr double logb(double x);
constexpr long double logb(long double x);
constexpr float lrint(float x);
constexpr double lrint(double x);
constexpr long double lrint(long double x);
constexpr float lround(float x);
constexpr double lround(double x);
constexpr long double lround(long double x);
constexpr float modf(float x, float* y);
constexpr double modf(double x, double* y);
constexpr long double modf(long double x, long double* y);
constexpr float nanf(const char* x);
constexpr double nan(const char* x);
constexpr long double nanl(const char* x);
constexpr float nearbyint(float x);
constexpr double nearbyint(double x);
constexpr long double nearbyint(long double x);
constexpr float nextafter(float x, float y);
constexpr double nextafter(double x, double y);
constexpr long double nextafter(long double x, long double y);
constexpr float nexttoward(float x, float y);
constexpr double nexttoward(double x, double y);
constexpr long double nexttoward(long double x, long double y);
constexpr float pow(float x, float y);
constexpr double pow(double x, double y);
constexpr long double pow(long double x, long double y);
constexpr float remainder(float x, float y);
constexpr double remainder(double x, double y);
constexpr long double remainder(long double x, long double y);
constexpr float remquo(float x, float y, int* z);
constexpr double remquo(double x, double y, int* z);
constexpr long double remquo(long double x, long double y, int* z);
constexpr float rint(float x);
constexpr double rint(double x);
constexpr long double rint(long double x);
constexpr float round(float x);
constexpr double round(double x);
constexpr long double round(long double x);
constexpr float scalbln(float x, long y);
constexpr double scalbln(double x, long y);
constexpr long double scalbln(long double x, long y);
constexpr float scalbn(float x, int y);
constexpr double scalbn(double x, int y);
constexpr long double scalbn(long double x, int y);
constexpr float sin(float x);
constexpr double sin(double x);
constexpr long double sin(long double x);
constexpr float sinh(float x);
constexpr double sinh(double x);
constexpr long double sinh(long double x);
constexpr float sqrt(float x);
constexpr double sqrt(double x);
constexpr long double sqrt(long double x);
constexpr float tan(float x);
constexpr double tan(double x);
constexpr long double tan(long double x);
constexpr float tanh(float x);
constexpr double tanh(double x);
constexpr long double tanh(long double x);
constexpr float tgamma(float x);
constexpr double tgamma(double x);
constexpr long double tgamma(long double x);
constexpr float trunc(float x);
constexpr double trunc(double x);
constexpr long double trunc(long double x);
constexpr double y0(double x);
constexpr double y1(double x);
constexpr double yn(int x, double y);
}